const prices=[1.79,2.19,2.59];
const priceData={1.79:{acceptance:61.7,channels:{dtc:[1.39,.77],retail:[1.02,.40],gym:[1.43,.81]}},2.19:{acceptance:51.7,channels:{dtc:[1.78,1.16],retail:[1.25,.63],gym:[1.75,1.13]}},2.59:{acceptance:26.7,channels:{dtc:[2.16,1.54],retail:[1.48,.86],gym:[2.07,1.45]}}};
const segments={"Urban Wellness Professionals":{n:112,intent:9.12,sens:3.63,spend:21.73,freq:7.56,channel:"DTC Online",quote:"I switched most of my afternoon coffee runs to something like this, I don't mind paying more for clean ingredients."},"Fitness & Gym-Goers":{n:83,intent:7.97,sens:5.44,spend:20.11,freq:6.23,channel:"Gym & Office",quote:"If it performs like VoltFit but tastes better I'm switching immediately."},"On-the-go Commuters":{n:90,intent:6.71,sens:5.98,spend:19.97,freq:5.87,channel:"Retail/Grocery",quote:"Grab and go is everything for me, if it's not at the kiosk near the station I'll never try it."},"Students & Budget-Conscious":{n:135,intent:5.50,sens:7.93,spend:17.24,freq:5.10,channel:"Retail/Grocery",quote:"If it's on promo near the exam period I'll grab a pack, otherwise it's a stretch."}};
const cities={Berlin:{n:81,intent:7.40,share:18,cagr:9,priority:27},Hamburg:{n:48,intent:7.52,share:10,cagr:7,priority:13},Munich:{n:57,intent:7.30,share:15,cagr:9,priority:13},Cologne:{n:45,intent:7.04,share:9,cagr:7,priority:16},Frankfurt:{n:32,intent:7.18,share:8,cagr:7,priority:6},"Other Germany":{n:157,intent:7.05,share:40,cagr:7,priority:37}};
const marketing={"Referral / Subscription":{cac:28.14,ltv:81.39,ratio:2.89},"Influencer / Content":{cac:37.53,ltv:100.82,ratio:2.69},"Paid Social":{cac:45.79,ltv:132.13,ratio:2.89},"Retail Sampling":{cac:60.13,ltv:174.17,ratio:2.90}};
const competitors=[['PulsUp',.96,1.28],['Mate Libre',1.37,1.83],['VoltFit',2.10,2.72],['Root & Rise',2.54,3.11]];
const $=id=>document.getElementById(id); const euro=n=>'€'+n.toFixed(2); const pct=n=>n.toFixed(1)+'%';
function init(){[['city',Object.keys(cities),'Berlin'],['segment',Object.keys(segments),'Urban Wellness Professionals'],['price',prices.map(p=>p.toFixed(2)), '2.19'],['marketing',Object.keys(marketing),'Referral / Subscription']].forEach(([id,vals,selected])=>{ $(id).innerHTML=vals.map(v=>`<option ${String(v)===selected?'selected':''}>${v}</option>`).join('');}); ['city','segment','price','marketing','dtc','gym','retail'].forEach(id=>$(id).addEventListener('input',render)); render();}
function render(){const p=Number($('price').value), city=$('city').value, seg=$('segment').value, m=$('marketing').value, mix={dtc:+$('dtc').value,gym:+$('gym').value,retail:+$('retail').value}; ['dtc','gym','retail'].forEach(k=>$(k+'-out').textContent=mix[k]+'%'); const total=Object.values(mix).reduce((a,b)=>a+b,0); $('mix-total').textContent=total+'%'; $('mix-total').style.color=total===100?'var(--green)':'var(--red)';
 const d=priceData[p], ch=d.channels; const valid=total===100; const weighted=(ch.dtc[1]*mix.dtc+ch.gym[1]*mix.gym+ch.retail[1]*mix.retail)/100; const net=(ch.dtc[0]*mix.dtc+ch.gym[0]*mix.gym+ch.retail[0]*mix.retail)/100; const margin=net?weighted/net*100:0; const md=marketing[m]; $('mix-warning').textContent=valid?'':'Invalid scenario: channel mix must equal 100% before channel economics or a management recommendation can be used.';
 $('rec-title').textContent=`${city} · ${seg} · ${euro(p)} per can`; let tone=p===2.19?'balanced':p<2.19?'acceptance-led':'margin-led'; let active=Object.entries(mix).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).map(([k])=>({dtc:'DTC Online',gym:'Gym & Office',retail:'Retail/Grocery'}[k])); let channelText=active.length?`Prioritize ${active[0]}${active[1]?' and '+active[1]:''}, with ${active[2]||'selective reach'} supporting the mix.`:'Select at least one sales channel.'; $('rec-text').textContent=valid?`${tone[0].toUpperCase()+tone.slice(1)} scenario: prioritize ${seg} in ${city}. ${channelText}`:'Scenario assessment unavailable until the channel mix equals 100%.';
 $('kpis').innerHTML=[['Acceptance',pct(d.acceptance),'Observed · price-test estimate'],['Weighted contribution',valid?euro(weighted):'Unavailable',valid?'Calculated · per unit':'Invalid mix'],['Contribution margin',valid?pct(margin):'Unavailable',valid?'Calculated · from net price':'Invalid mix'],['CAC benchmark',euro(md.cac),'Historical · marketing benchmark'],['LTV:CAC',md.ratio.toFixed(2)+'×','Historical estimate · not payback']].map(x=>`<div class="kpi"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="detail">${x[2]}</div></div>`).join('');
 $('price-chart').innerHTML=prices.map(x=>{let z=priceData[x];let avg=(z.channels.dtc[1]+z.channels.retail[1]+z.channels.gym[1])/3;return `<div class="bar-row ${x===p?'selected':''}"><span>€${x.toFixed(2)}</span><div class="track"><div class="fill" style="width:${z.acceptance}%"></div></div><small>${pct(z.acceptance)} · ${euro(avg)} avg</small></div>`}).join('');
 $('channel-chart').innerHTML=[['DTC Online','dtc'],['Gym & Office','gym'],['Retail/Grocery','retail']].map(([label,k])=>`<div class="bar-row ${mix[k]>0?'selected':''}"><span>${label}</span><div class="track"><div class="fill" style="width:${ch[k][1]/1.6*100}%"></div></div><small>${euro(ch[k][1])} · ${pct(ch[k][1]/ch[k][0]*100)}</small></div>`).join('');
 const s=segments[seg]; $('segment-title').textContent=seg; $('segment-evidence').innerHTML=`<div class="evidence"><div class="metric"><b>${s.intent.toFixed(2)}/10</b><span>average purchase intent</span></div><div class="metric"><b>${s.sens.toFixed(2)}/10</b><span>price sensitivity</span></div><div class="metric"><b>€${s.spend.toFixed(2)}</b><span>monthly beverage spend</span></div><div class="metric"><b>${s.freq.toFixed(2)}</b><span>purchases per month</span></div></div><p class="caption"><b>Preferred channel:</b> ${s.channel}<br><b>Useful quote:</b> “${s.quote}”</p>`;
 const c=cities[city]; $('city-title').textContent=city; $('city-evidence').innerHTML=`<div class="evidence"><div class="metric"><b>${c.share}%</b><span>illustrative market share</span></div><div class="metric"><b>${c.cagr}%</b><span>illustrative regional CAGR</span></div><div class="metric"><b>${c.intent.toFixed(2)}/10</b><span>city survey intent</span></div><div class="metric"><b>${c.priority}</b><span>priority-segment respondents</span></div></div><div class="city-rank"><span>Berlin · primary recommendation</span><strong>18% share</strong></div><div class="city-rank"><span>Hamburg · wellness test</span><strong>7.52 intent</strong></div><div class="city-rank"><span>Munich · fitness test</span><strong>9% CAGR</strong></div>`;
 $('competitor-chart').innerHTML=competitors.map(x=>`<div class="comp"><span>${x[0]}</span><div class="comp-track"><div class="comp-range" style="left:${x[1]/3.5*100}%;width:${(x[2]-x[1])/3.5*100}%"></div></div><small>€${x[1].toFixed(2)}–€${x[2].toFixed(2)}</small></div>`).join('')+`<div class="comp lumen"><span><b>LUMEN</b></span><div class="comp-track"><div class="comp-range" style="left:${p/3.5*100}%;width:3px"></div></div><small><b>€${p.toFixed(2)}</b></small></div>`;
 $('marketing-title').textContent=m; $('marketing-evidence').innerHTML=`<div class="evidence"><div class="metric"><b>${euro(md.cac)}</b><span>historical CAC</span></div><div class="metric"><b>${euro(md.ltv)}</b><span>estimated LTV</span></div><div class="metric"><b>${md.ratio.toFixed(2)}×</b><span>LTV:CAC benchmark</span></div><div class="metric"><b>${m==='Referral / Subscription'?'Priority':'Test selectively'}</b><span>planning role</span></div></div>`;
 $('cmo').textContent=valid?(p===2.19?'€2.19 places LUMEN in premium-performance territory while keeping acceptance materially above €2.59.':p<2.19?'€1.79 supports trial, but risks weakening premium signaling.':'€2.59 maximizes unit margin, but its 26.7% acceptance estimate makes adoption the key risk.'):'Assessment paused until the channel mix is valid.'; $('cfo').textContent=valid?`The selected mix produces ${euro(weighted)} contribution per unit and ${pct(margin)} contribution margin before marketing. ${m} has a ${euro(md.cac)} historical CAC benchmark.`:'Channel economics are withheld because the mix does not equal 100%.'; $('limits').textContent='No German volume, revenue, retention, customer-level attribution, or time-to-payback is available. LTV:CAC is a benchmark, not a payback period.';}
init();
